#!/bin/zsh

uuids=( $(adb devices) )
echo $uuids

if [[ $2 == starbucks ]]; then
	#statements
	appname="Starbucks-stagUnpinned-release.apk"
	appIdentifier="com.starbucks.cn"
else 
	appname=$2
	appIdentifier=$2
	#statements
fi

case $1 in
	"install" )
		for uuid in $uuids; do
			#statements
			echo installing $appname to $uuid
			adb -s $uuid install $appname
		done
		;;
	"uninstall" )
		for uuid in $uuids; do
			#statements
		echo uninstalling $appIdentifier from $uuid
		adb -s $uuid uninstall $appIdentifier
		done
		;;
esac
