#!/bin/zsh

build=$1
appname="Starbucks-stagUnpinned-release.apk"
AppToken=yourToken
AppId=yourID
download_url=($(curl -H "X-HockeyAppToken: $AppToken" "https://rink.hockeyapp.net/api/2/apps/$AppId/app_versions?include_build_urls=true" | python script.py $build))

echo downloading build $build from $download_url

curl -o $appname -L $download_url

uuids=( $(adb devices) )
useless_info=( List of devices attached device)
for delete in ${useless_info[@]}; do
	#statements
	uuids=("${uuids[@]/$delete}")
done
echo uuids $uuids

for uuid in $uuids; do
	#statements
	echo installing $appname to $uuid
	adb -s $uuid install -r $appname
done

