# Uncomment the next line to define a global platform for your project
# platform :mac, '10.0'

target 'Access' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Access
  pod 'Moya', '~> 11.0'

end
